# This an example config
# All available options for writing test scenarios are present
server: 127.0.0.1
port: 5301
domain: bench.test
protocol: udp
queries: 50000
workers: 8
mode: count
rdatatypes:
    - A
    - AAAA
    - MX
    - NS
    